version: '3.5'

services:
    bridge:
      build: ../micromobility_bridgecontainer/Docker
      image: micromobility_bridgecontainer:latest
      container_name: micromobility_bridgecontainer
      #entrypoint: /bin/bash -c 'node bin/rosbridge.js'
      ports:
        - 9090:9090
        - 3001:3000
      restart: always
      stdin_open: true # docker run -i
      tty: true        # docker run -t
